---
title: "semester-project-group9"
format: html
editor: visual
bibliography: bibliography.bib
---

## Abstract

This work explores the possibility of determine the perception of route choice of bike messengers in the city of Zurich. This is done by comparing chosen trajectories with auto generated alternative trajectories. We compare paths of chosen routes (deliveries) with a the generated set of modeled routes (choice-set/alternatives) in terms of distance traveled, maximum slope and street width Our analysis is based on 95 shift performed by 2 messengers. Street network and street type and were taken from the Swisstlm3d data set. For further attributes such as slope, the DHM25 was considered.

## Introduction

Route choice models play an important role in many transport applications, for example, intelligent transport systems, GPS navigation and transportation planning [@frejinger_route_2007]. Modeling route choice behavior is essential, given the possibility to appraise travelers perceptions of route characteristics and to forecast travelers' behavior under hypothetical scenarios [@prato_route_2009]. Route choice models can assess travelers' perceptions of various route characteristics such as distance, travel time, cost, number of traffic lights and road types, and relate the results to the individuals' characteristics (e.g. gender, age, income and trip purpose) and can not only help analyzing and understanding travelers' behavior, but also constitute the essential part of traffic assignment methods. Several studies have used route choice modelling to investigate preferences of cyclists in cities for different purposes such as effectiveness of investments in bicycle infrastructure [@hood_gps-based_2011]. @skov-petersen_how_2018-1 investigated route choices by cyclists in Copenhagen (Denmark). The authors found that cyclists expressed a negative utility for length and turns, indicating a preference for shorter and more direct routes. Furthermore they were sensitive to factors such as length, cycling the wrong way, turn frequency, and terrain gradient. @broach2012cyclists applied various route choice methods to generate routes in Portland. The results reported in the study showed that only 25% of the generated routes replicated the actual routes, and 42.3% of the routes with an 80% overlap. @hood_gps-based_2011 applied the simulation method to generate routes (the doubly stochastic method) in San Francisco. In contrast to other studies, they added environmental and socioeconomic variables to the cost function, such as crime hot-spots, light and weather conditions. However, as in @broach2012cyclists, the capture rates were very low (around 30%). @menghini2009route used the angle elimination method to generate routes in Zurich.The cost function used was limited to driving distance. In the study by @halldorsdottir2014efficiency in Copenhagen, the cost functions included land use and road type. They added a random component to these values to create a representative route choice set. The coverage results (70 %) were better compared to the previous studies. This work takes a different approach, exploring the route choices of bike messengers instead of analyzing the route choice of commuters or leisure cyclists. Analyzing the route choices of bike messengers compared to ordinary cyclists can provide insights into efficiency and safety. Due to the fact that bike messengers, are often under time pressure and have a excellent knowledge of the street network, they may choose faster routes, even if they are longer in terms of distance. Additionally, as experienced cyclists, bike messengers can also choose safer or less traveled routes, which can lead to conclusions for the general safety of all cyclists in cities. Furthermore, routes chosen by bike messengers can offer important data on the usage of the city's cycling infrastructure. This can guide decisions on where to focus improvements and enhance route planning and traffic management.

## Research Questions

1.  Do bike messengers always choose the shortest possible route during their deliveries? Efficiency in terms of travel distance

2.  How do street network attributes influence the route choice behavior of bike messengers in Zurich? Efficiency in terms of an optimized cost-path ratio

3.  Is there a combination of above criteria that would be preferable in terms of speed/convenience?

## Data

### GPS Data

We utilized GPS data collected with the fitness-tracking-app Strava[^1] . The data was collected by two bike messengers in Zurich and conducted as GPX files. The two messengers have been assigned aliases for the purpose of this analysis. They are referred to as `donner` and `raeubertochter`. The data encompasses 95 shifts, with each shift including multiple trajectories/deliveries. The raw data contains a total number of xyz data points. The shifts vary in terms of distance traveled, working hours, season, weather and the number of deliveries.

[^1]: https://www.strava.com/dashboard

### Context Data

All contextual data for enriching the route network is sourced from open-source platforms. SwissTLM3D[^2] provided the street network, street type, and width. The digital terrain model (DHM25)[^3] was used for obtaining the slope of the streets. DHM25 is available with a resolution of 0.5 meters.

[^2]: https://www.swisstopo.admin.ch/de/landschaftsmodell-swisstlm3d

[^3]: https://www.swisstopo.admin.ch/de/hoehenmodell-dhm25

## Methods

### Segmentation

The segmentation of GPS data into different segments was achieved by analyzing the time differences between consecutive data points. (source) Since the Strava-App data already eliminates most static points, it allowed us to rely solely on significant time gaps for the segmentation. Thus, a moving time window was created for each route, and the mean time difference was calculated for each messenger. A new segment was then defined as any instance where the mean time difference exceeded a threshold of 20 seconds. The data was further refined by removing static rows and any segments shorter than two minutes. Each segment was then assigned a `segment ID`, and the number of differentiated segments was calculated for each messenger. Resulting in 36 deliveries for `donner`, and 22 deliveries for `raeubertochter`.

### Map Matching

Map matching denotes the process of assigning positional data (mostly in form of GPS coordinates) to some geographic information about the infrastructure, most commonly road networks [@meister_descriptive_2021]. In our map matching process, we used distance-based matching of a point to a road which return the edges that are closest to the trajectory. geometrically we unified all roads into a single network. We then located the nearest point on this network for each GPS location and were then used to update the original GPS locations, effectively mapping each GPS point to its closest location on the road network.

### Alternative Trajectories

We used the HERE API to generate alternative routes based on these points. The hereR[^4] package provides an interface to the HERE REST APIs for R. The route function from the hereR package was used to generate the alternative routes and enabled the calculation of a maximum of 7 alternative routes. ´route()´ enables to calculate route geometries (LINESTRING) between given pairs of points. Routes can be created for various transport modes, as for example 'car' or 'bicycle'.

Bei der Berechnung der alternativen trajectories erhielten wir, Aufgrund der täglichen Begrenzung von Berechnungen, eine Liste von 2819 Entitäten. Diese enthielten unterschiedlich viele alternative trajectories, je nachdem, ob es für Sinnvoll erhalten wurde

[^4]: https://www.rdocumentation.org/packages/hereR/versions/1.0.0.

### Uneven distribution and Interpolation

We encountered a challenge due to the unequal distribution of data points and granularity within original routes and also between alternative routes. As derived movement parameters are strongly influenced by the sampling rate, can skew calculations due to smaller intervals in original routes detecting more differences in height or slope than wider intervals in alternative routing [@laube_how_2011]. To solve this issue, we interpolated along the trajectories. We simplified the dataset, transformed it into a linestring, and created an interpolation function. We then applied this function to each linestring, unnested the points, and manipulated the geometry of the points. This resulted in an even distribution between alternatives and original routes.

### Slope

Many permutations of elevation change and slope were tested, including cumulative gain and loss, average and maximum slope, and several non-linear slope variables. The best performing specification was proportion of route length within three categories of average positive slope (gain/distance): 2–4%, 4–6%, and 6%. For example, a link traversing 500 ft (150 m) with 10 ft (3 m) gross gain along the traversal would have an average upslope of 2% and would be coded as 500 ft (150 m) in the 2–4% upslope category. Our model indicates that a cyclist would be willing to pedal 1.72 flat miles (1.37 miles commuting) if the alternative were 1 mile of 2–4% upslope [@broach2012cyclists].

## Descriptive Analysis

## Results

## Discussion

## Problems / Limitations

### Map matching sucks

due to certain constraints and available resources, we adopted a simple approach of distance-based point-to-road matching, which has been identified with several limitations [@meister_descriptive_2021]. More sophisticated methods, such as the one proposed by @newson2009hidden that employs Hidden Markov Models (HMMs), are more effective as they consider factors like measurement noise and the structure of the road network, thereby avoiding the simplistic distance-based point-to-road matching. For implementing map matching in intricate urban road networks, it's crucial to use map matching tools that consider various sources of error linked with position sensors, the vehicle's historical trajectory, topological data about the road network (for instance, link connectivity and alignment), and the vehicle's direction and speed. These factors collectively help in accurately determining the correct link where the vehicle is located [@ochieng_map-matching_2003].

### Critical reflection

Uneven distributions - interpolation. Too many data points in one sample AND irregular sampling as a challenge. Perhaps the most widely used approach is to transform unevenly spaced data into equally spaced data using some form of interpolation. Transforming data with linear interpolation, however, can have significant drawbacks, such as bias, data loss or dilution [@eckner_framework_2014]. However, when applied to our specific data and the research question to be answered, these concerns were considered reasonable.

### Approach in generating alternative trajectories

One problem that comes with using an algorithm to generate alternative trajectories is the creation of a share of unreasonable trajectories. One has to consider this source of error as the aim is to create trajectories that represent plausible alternatives. Thus research is aimining to improve network-based automatic calibration of the ``doubly stochastic” method of @Hood2012. This method produces more heterogeneous, attractive, unbiased, and exhaustive choice sets than other methods, yielding more reliable parameter estimates and predictions.


### References

::: {#refs}
:::
=======
### Limitations in generating alternative trajectories
